-- | Scoped local Droid sessions. The shared runtime owns RPC correlation,
-- callbacks, turns and cleanup; see Factory.Droid.Daemon for existing daemons.
module Factory.Droid
  ( DroidOptions (..),
    defaultDroidOptions,
    DroidSession,
    DroidSessionStatus (..),
    droidSessionStatus,
    onDroidSessionEvent,
    DroidReplacementError (..),
    DroidRewindOptions (..),
    droidSessionId,
    DroidResult (..),
    DroidEvent (..),
    DroidStreamMode (..),
    DroidInput (..),
    droidInput,
    DroidOutput,
    DroidOutputError (..),
    DroidOutputResult (..),
    rawDroidOutput,
    jsonDroidOutput,
    SystemPromptConfig,
    customSystemPrompt,
    appendedSystemPrompt,
    DroidError (..),
    DroidHandlers (..),
    defaultDroidHandlers,
    DroidInteraction (..),
    DroidInteractionFailure (..),
    DroidMcpFailure (..),
    withDroidSession,
    withResumedDroidSession,
    withDroidSessionHandlers,
    withResumedDroidSessionHandlers,
    sendPrompt,
    sendDroidTurn,
    sendDroidEvents,
    sendDroidOutput,
    sendDroidOutputEvents,
    sendDroidInput,
    sendDroidInputEvents,
    sendDroidInputOutput,
    sendDroidInputOutputEvents,
    interruptDroidSession,
    runDroid,
    streamDroid,
    listDroidModels,
    listDroidTools,
    listDroidCommands,
    listDroidSkills,
    listDroidMcpServers,
    listDroidMcpTools,
    listDroidMcpRegistry,
    addDroidMcpServer,
    removeDroidMcpServer,
    toggleDroidMcpServer,
    toggleDroidMcpTool,
    authenticateDroidMcpServer,
    cancelDroidMcpAuth,
    clearDroidMcpAuth,
    submitDroidMcpAuthCode,
    submitDroidMcpAuthError,
    getDroidSettings,
    updateDroidSettings,
    setDroidSkillDisabled,
    getDroidContextStats,
    getDroidContextBreakdown,
    renameDroidSession,
    changeDroidWorkingDirectory,
    getDroidRewindInfo,
    forkDroidSession,
    compactDroidSession,
    rewindDroidSession,
  )
where

import Factory.Droid.Internal.Session
